### ISSUE TITLE
issue() 메소드에 관한 주석이 잘못된 것 같습니다.

### ISSUE THREAD

**Issue by icepeng** [linkhub-sdk/node-popbill.example#1]
https://github.com/linkhub-sdk/node-popbill.example/blob/767c0d9a731daadbca76578b64ef5bb5144d9b40/routes/taxinvoice.js#L1570-L1605

https://github.com/linkhub-sdk/node-popbill.example/blob/767c0d9a731daadbca76578b64ef5bb5144d9b40/routes/taxinvoice.js#L1607-L1634

두개의 예제에 동일한 설명이 적혀있습니다.

**Comment by khjzzm** [comment]
세금계산서 발행(issue) commnets 수정
