### ISSUE TITLE
getInfos 에서는 itemKey를 돌려주나 getDetailInfo 에서는 돌려주고 있지 않습니다

### ISSUE THREAD

**Issue by granberia** [linkhub-sdk/node-popbill.example#2]
수정세금계산서 발행시 원본 itemKey 및 상세 정보가 필요하나 getDetailInfo 에서는 itemKey를 돌려주지 않으며, getInfos 에서는 상세 정보를 돌려주지 않습니다. 특정 invoicerMgtKey의 세금계산서로부터  itemKey와 상세 정보를 한 번에 받아올 방법이 있을까요?

**Comment by JohnJeong123** [comment]
@granberia 안녕하세요. 링크허브 기술지원팀 정요한입니다. 

수정세금계산서 발행을 위해서는 우선 getInfo API를 사용하여 세금계산서 상태코드(stateCode)를 확인하고, 국세청 전송여부에 따라 수정세금계산서 발행 또는 발행취소 처리를 할 수 있습니다. 

예를들어 아직 국세청에 전송되지 않은 [발행완료] 상태의 세금계산서를 수정해야하는 경우 [발행취소(CancelIssue)] 후 세금계산서를 다시 작성하여 발행하시고 

국세청에 전송이 완료된 [전송성공] 상태의 세금계산서를 수정해야하는 경우 수정세금계산서 발행을 진행하시면 됩니다. 

어떤 경우라도 GetInfo를 통해 StateCode 를 확인하는 과정이 필요하기 때문에 StateCode 를 확인하는 로직에서 ItemKey를 확인하시면 됩니다. 

추가적인 문의사항이 있으시면

언제든 연락주시기 바랍니다. 감사합니다. 


링크허브 기술지원팀 정요한 과장 (D. 1600-9854 / E. code@linkhub.co.kr )
