### ISSUE TITLE
issue() 메소드 예제에 오류가 있는 것 같습니다.

### ISSUE THREAD

**Issue by icepeng** [linkhub-sdk/node-popbill.example#3]
https://github.com/linkhub-sdk/node-popbill.example/blob/b1a349d011fe5517ac95f927771066c2c0e2f236/routes/taxinvoice.js#L1595-L1601

해당 코드에서는 `ForceIssue`는 인자에 포함되어 있으나, `UserID`를 인자로 넘기지 않고 있습니다. 하지만 `node-popbill`의 구현을 보면

https://github.com/linkhub-sdk/node-popbill/blob/ded74ad7d16d541e5bc384fa5a2049b80f0e1c77/lib/TaxinvoiceService.js#L518-L534

오버로딩 된 함수 중 어떤것도 `ForceIssue`를 받으면서 `UserID`를 받지 않는 것은 없습니다.

따라서, 해당 예제를 그대로 실행하면 `UserID`가 `false`인 채로 요청을 보내게 됩니다. 신기하게도 이 경우는 요청에 성공합니다.

하지만 `UserID`를 `true`로 바꿔서 요청하면 "인증키와 사용자아이디로 사용자를 식별할 수 없습니다." 와 같은 에러를 돌려줍니다.

`node-popbill`의 코드를 살펴본 결과

https://github.com/linkhub-sdk/node-popbill/blob/ded74ad7d16d541e5bc384fa5a2049b80f0e1c77/lib/BaseService.js#L232

에서 `if (options.UserID)` 조건으로 헤더를 추가하는 것이 문제로 추정됩니다.

결론적으로, 예제에서 인자를 올바르게 넘기도록 수정하고, `node-popbill` 패키지의 코드 또한 `if (options.UserID === "")`으로 수정하는 것이 좋다고 생각합니다.

**Comment by JohnJeong123** [comment]
@icepeng 안녕하세요. 링크허브 기술지원팀 정요한입니다. 

먼저 저희 API 서비스를 이용하시는데 불편끼쳐드려 죄송합니다.

이야기해주신 SDK 상의 버그를 최대한 빠르게 수정하도록 하겠습니다. 

감사합니다.

**Comment by icepeng** [comment]
빠른 답변 고맙습니다.

코드와 관계없는 내용이지만, 팝빌 개발용 사이트에서 발행 테스트를 할 때마다 포인트가 차감되고 있는데 포인트가 0이 되어도 계속 발행 가능한가요?

**Comment by JohnJeong123** [comment]
@icepeng 개발용에서 지원해드리는 포인트는 링크허브 파트너지원센터로(1600-9854)로 연락주시면 보너스 포인트 충전처리를 해드리고 있습니다.
